spring:
  application:
    name: springboot-graphql

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2

  sql:
    init:
      mode: always

  h2:
    console:
      path: /h2-console
      enabled: true

  graphql:
    graphiql:
      enabled: true # default : false
      path: /graphiql # default : graphiql
    schema:
      printer:
        enabled: true # like JPA show-sql

server:
  port: 8888

cors:
  allowed:
    mapping: "/**"
    origins: "*" # Client Server URL
    headers: "*"
    methods: POST, GET, PATCH, DELETE, OPTIONS, PUT

logging:
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%-5p][%thread][%logger{0}.%method] - %msg%n"

  file:
    name: ./logs/graphql.log

  level:
    org.hibernate:
      SQL: debug
      orm:
        jdbc:
          bind: trace
    root: info

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: "${LOG_FILE}%d{yyyy-MM-dd_HH}-%i.log" # 매 시마다 롤링.