spring:
  application:
    name: springboot-graphql

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2

  sql:
    init:
      mode: always

  h2:
    console:
      path: /h2-console
      enabled: true

  graphql:
    graphiql:
      enabled: true # localhost:8888/graphiql
    schema:
      printer:
        enabled: true # like JPA show-sql

server:
  port: 8888

cors:
  allowed:
    mapping: "/**"
    origins: "*" # Client Server URL
    headers: "*"
    methods: POST, GET, PATCH, DELETE, OPTIONS, PUT